import { callClaude, getLevelContext, claudeErrorResponse } from '../../../lib/claude';
import { checkRateLimit, recordApiUsage, RATE_LIMIT_MESSAGE } from '../../../lib/rateLimit';
import { SOCRATIC_TUTOR_RULES } from '../../../lib/socraticTutor';

// Same retry/timeout architecture as every other AI route - explicit
// maxDuration so a worst-case double-timeout retry always has room to
// finish and return a clean error response instead of Vercel's own
// function-duration limit killing it first.
export const maxDuration = 60;

export async function POST(req) {
  try {
    const { question, studentWorking, markingResult, topic, history, message, course, board, difficulty, accessToken, image } = await req.json();

    const rateCheck = await checkRateLimit(accessToken);
    if (rateCheck.error) return Response.json({ error: rateCheck.error }, { status: rateCheck.status });
    if (rateCheck.limited) return Response.json({ error: RATE_LIMIT_MESSAGE, code: 'own_rate_limit' }, { status: 429 });

    const { courseInfo, boardInfo, difficultyInfo, specCode, furtherMathsNote } = getLevelContext(course, board, difficulty);
    // This route serves several callers - the post-marking "ask about it"
    // thread, the main thread's floating-chat use with an active but
    // not-yet-marked question, and the general "Maths Help" launcher with
    // no app question at all (a student's own homework/textbook/exam
    // problem). The split that actually matters is markingResult, not
    // question: once marking has happened, discussing what was already
    // fed back is fine and expected - it's any NEW or still-ongoing problem
    // (app-generated or the student's own) that gets the strict Socratic
    // treatment, never just handing over the answer.
    // Only added to the prompt when a photo is actually attached, so the
    // vast majority of text-only messages don't carry unused boilerplate.
    const imageNote = image
      ? ' The student may attach a photo of their own handwritten or textbook problem - read it carefully, and apply the same rule as always: never just solve it for them, guide them through it.'
      : '';
    // Lets the chat bubble render real typeset maths (see
    // app/components/MathText.js) instead of raw text like x^2 or 3/4.
    const mathNote = ' When writing mathematical expressions, use LaTeX delimiters: wrap inline maths in single dollar signs (e.g. $x^2$) and standalone/display equations in double dollar signs (e.g. $$\\frac{a}{b}$$) - keep regular sentence text outside these delimiters as normal plain English.';
    const system = markingResult
      ? `You are a warm, patient maths tutor for ${boardInfo.label} (${specCode}). ${courseInfo.levelDescription} This question was set at the following difficulty: ${difficultyInfo.promptHint}${furtherMathsNote} The student has just received marked feedback on their working for this question and is asking a follow-up about it - explain in plain English, use small worked examples if helpful, and check for understanding rather than lecturing. Keep replies fairly short (a few sentences) unless a fuller explanation is clearly needed. Do not just repeat the feedback already given verbatim - actually explain the underlying idea.${imageNote}${mathNote} Return plain text, not JSON.`
      : `You are a patient maths tutor helping a student work through a problem - which may be one generated by this app, or a problem the student has brought from their own homework, textbook, or exam paper. For rough calibration, they're generally working at around ${boardInfo.label} (${specCode}) level: ${courseInfo.levelDescription}${furtherMathsNote} ${SOCRATIC_TUTOR_RULES}${imageNote}${mathNote} Return plain text, not JSON.`;

    const contextLines = [];
    if (question) contextLines.push(`Original question: ${question}`);
    if (studentWorking) contextLines.push(`Student's working so far:\n${studentWorking}`);
    if (markingResult) contextLines.push(`Marking result: ${JSON.stringify(markingResult)}`);
    if (!question && topic) contextLines.push(`Topic: ${topic}`);
    contextLines.push(`Conversation so far:\n${(history || []).map((m) => `${m.role === 'user' ? 'Student' : 'Tutor'}: ${m.content}`).join('\n')}`);
    contextLines.push(`Student's new message: ${message || '(sent a photo, no typed message)'}`);
    const context = contextLines.join('\n\n');

    // When a photo is attached, the message sent to Claude becomes a
    // content array (image block + text block) instead of a plain string -
    // callClaude passes userText straight through as the message content,
    // which the Messages API accepts as either shape.
    const userText = image
      ? [
          { type: 'image', source: { type: 'base64', media_type: image.mediaType, data: image.base64 } },
          { type: 'text', text: context }
        ]
      : context;

    const reply = await callClaude({ system, userText, expectJson: false });
    await recordApiUsage(rateCheck.supabase, rateCheck.userId, 'chat');
    return Response.json({ reply });
  } catch (err) {
    const { body, status } = claudeErrorResponse(err);
    return Response.json(body, { status });
  }
}
