import { callClaude, getLevelContext, claudeErrorResponse } from '../../../lib/claude';
import { checkRateLimit, recordApiUsage, RATE_LIMIT_MESSAGE } from '../../../lib/rateLimit';

// Same retry/timeout architecture as every other AI route - explicit
// maxDuration so a worst-case double-timeout retry always has room to
// finish and return a clean error response instead of Vercel's own
// function-duration limit killing it first.
export const maxDuration = 60;

export async function POST(req) {
  try {
    const { question, studentWorking, markingResult, topic, history, message, course, board, difficulty, accessToken } = await req.json();

    const rateCheck = await checkRateLimit(accessToken);
    if (rateCheck.error) return Response.json({ error: rateCheck.error }, { status: rateCheck.status });
    if (rateCheck.limited) return Response.json({ error: RATE_LIMIT_MESSAGE, code: 'own_rate_limit' }, { status: 429 });

    const { courseInfo, boardInfo, difficultyInfo, specCode, furtherMathsNote } = getLevelContext(course, board, difficulty);
    // This route serves several callers - the post-marking "ask about it"
    // thread, the main thread's floating-chat use with an active but
    // not-yet-marked question, and the general "Maths Help" launcher with
    // no app question at all (a student's own homework/textbook/exam
    // problem). The split that actually matters is markingResult, not
    // question: once marking has happened, discussing what was already
    // fed back is fine and expected - it's any NEW or still-ongoing problem
    // (app-generated or the student's own) that gets the strict Socratic
    // treatment, never just handing over the answer.
    const system = markingResult
      ? `You are a warm, patient maths tutor for ${boardInfo.label} (${specCode}). ${courseInfo.levelDescription} This question was set at the following difficulty: ${difficultyInfo.promptHint}${furtherMathsNote} The student has just received marked feedback on their working for this question and is asking a follow-up about it - explain in plain English, use small worked examples if helpful, and check for understanding rather than lecturing. Keep replies fairly short (a few sentences) unless a fuller explanation is clearly needed. Do not just repeat the feedback already given verbatim - actually explain the underlying idea. Return plain text, not JSON.`
      : `You are a patient maths tutor helping a student work through a problem - which may be one generated by this app, or a problem the student has brought from their own homework, textbook, or exam paper. For rough calibration, they're generally working at around ${boardInfo.label} (${specCode}) level: ${courseInfo.levelDescription}${furtherMathsNote} Your firm rule: NEVER state the final answer or complete a calculation step on the student's behalf, even if asked directly or repeatedly. Instead: if they haven't started, ask what they think the first step should be, or give a small nudge toward it - never do it for them. If they attempt a step and get it right, confirm briefly and ask them to continue with the next step themselves. If they attempt a step and get it wrong, explain what's gone wrong conceptually (without doing the corrected step for them) and ask them to try that step again. If a student explicitly and repeatedly insists on just being told the answer (after at least 3-4 genuine back-and-forth exchanges on the same problem), you may walk through the full method step by step - but still frame it as teaching the method, not simply stating a bare final answer with no working shown. Keep responses short and conversational, like a real tutor sitting next to them - not a lecture. Return plain text, not JSON.`;

    const contextLines = [];
    if (question) contextLines.push(`Original question: ${question}`);
    if (studentWorking) contextLines.push(`Student's working so far:\n${studentWorking}`);
    if (markingResult) contextLines.push(`Marking result: ${JSON.stringify(markingResult)}`);
    if (!question && topic) contextLines.push(`Topic: ${topic}`);
    contextLines.push(`Conversation so far:\n${(history || []).map((m) => `${m.role === 'user' ? 'Student' : 'Tutor'}: ${m.content}`).join('\n')}`);
    contextLines.push(`Student's new message: ${message}`);
    const context = contextLines.join('\n\n');

    const reply = await callClaude({ system, userText: context, expectJson: false });
    await recordApiUsage(rateCheck.supabase, rateCheck.userId, 'chat');
    return Response.json({ reply });
  } catch (err) {
    const { body, status } = claudeErrorResponse(err);
    return Response.json(body, { status });
  }
}
